dist: bionic
language: java
jdk:
 - openjdk15
env:
 global:
  - secure: "XuiCH1ubDI0PNNryxsHTQ3/EJ3ltTuYftWin7VFmOCNdXs8r1kmSeIlEuC3kT+Lbwl7ycTvGJH5ZF6JvVWijfb/aoKuBrfn0dbOygmoHpvJwK+Ho4K4WTu9gmH+SUfVylTmySThoyECV5PHMdfQQ+dPGFxnAXAxhvFodIfMc8CZAD+TOQhlv6JA1PkmidvWyPeYF+c0G0nUEWxHlD1OU2/ZYP6KdcyMNVmg/so8xhmLUC+8+lBH1cHpIzOABpYFXUaZj34Nj7QGb8uXDbckvUP9JkUSfIW95y2/zQXjz3fbK/oNU39uMSt3K0GnnEiG23igIrTVtirJQJNMDfmZMAXkrkzQUEYDchlc83hMEiO8mxuOhwfs1lvYBKLPMIBjMhy82oYvtjjmO2gd65zYhgZMkBt2tHXMi/MuHlQcuVp/LjkOiTQ4Mi1dRN//viJgvXWAT6XtYPxi4DdVONgxzyQTlIy6Aw/xMFkC5G5ThPC6yidBa+hCFPq5UES7IOB56MmPYHlOd9kYvRKKC3xoqs5J8EqMfk896mYYTNe2obk3G114kQKQP8W0trnsMQehtW29MFB0QU28a26EV7kvTqAK/byAwBUr3I/cJbK/45hseLaIkv0VSfsOhtBCHmPZVt3Hrmrpxu+E6lWd6SG8NJ08DG5Q6/i7L2dFXGFXERuk="
cache:
 directories:
  - $HOME/.m2
script:
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
 - mvn -T 1C -f releng/edu.toronto.cs.se.modelepedia.libz3java.releng/pom.xml clean install
 - mvn -T 1C -f releng/edu.toronto.cs.se.mmint.releng/pom.xml clean install
after_success:
 - >
   test $TRAVIS_PULL_REQUEST = false &&
   git clone https://github.com/ellachang/ellachang.github.io.git &&
   cd ellachang.github.io &&
   rm -rf mmint/${TRAVIS_BRANCH/master/release} &&
   mv $TRAVIS_BUILD_DIR/releng/edu.toronto.cs.se.mmint.install/target/repository mmint/${TRAVIS_BRANCH/master/release} &&
   git add . &&
   git reset --soft HEAD~1 &&
   git commit --author="Ella Chang <ellachang1002@outlook.com>" -m "mmint: Update builds" &&
   git push -f -q https://ellachang:$MMINT@github.com/ellachang/ellachang.github.io.git master &> /dev/null
